### ISSUE TITLE
Install make

### ISSUE THREAD

**Issue by webteckie** [million12/docker-centos-supervisor#6]
Can you please install make in the image?  Thanks in advance!  Getting the following error in my build:

```
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/lib/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/lib/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:108:15)
gyp ERR! System Linux 4.0.3-boot2docker
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by ryzy** [comment]
Hi,

Build tools are pretty heavy to add them to such a base image as this one (AFAIR they'd at least double its size). You don't have there node-gyp as well, so I guess you're going to build own image based on this one. Why not install there build tools?

PS. Sometimes you'll need build tools only during `docker build` to install/compile some tools. I usually do that by installing them, doing the necessary magic to install my stuff, then remove them. All in single `RUN` command.

**Comment by webteckie** [comment]
@ryzy thanks for the reply.  I was not implying install the entire dev tools package but just make, which is common for things to get built upon install.  node-gyp is something particular to me and gets installed by npm.  But I understand your concerns in trying to keep a tiny image!  If after this comment you still feel strongly about not having make in the base image then feel free to close.  FYI, yes, I can install make on my own image:

```
Step 12 : RUN yum -y install gcc gcc-c++ make
 ---> Running in 26baf5ca504f
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.web-ster.com
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.5ninesolutions.com
 * updates: mirror.cs.vt.edu
Package gcc-4.8.3-9.el7.x86_64 already installed and latest version
Package gcc-c++-4.8.3-9.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package make.x86_64 1:3.82-21.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package        Arch             Version                   Repository      Size
================================================================================
Installing:
 make           x86_64           1:3.82-21.el7             base           420 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 420 k
Installed size: 1.1 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:make-3.82-21.el7.x86_64                                    1/1
  Verifying  : 1:make-3.82-21.el7.x86_64                                    1/1

Installed:
  make.x86_64 1:3.82-21.el7
```
